name: toolkit
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - bioconda
dependencies:
  - pandas
  - typing
  - pytest
  - pytest-mock
  - black
prefix: C:\Users\leong\anaconda3\envs\toolkit
